made Changes in buildSpecFile and added unitTest Logic

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,11 +1,18 @@
 steps:
 - name: 'gcr.io/cloud-builders/mvn'
   entrypoint: 'mvn'
+  args: ['clean', 'test'] # Run unit tests
+- name: 'gcr.io/cloud-builders/mvn'
+  entrypoint: 'mvn'
   args: ['clean', 'install']
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: 'bash'
-  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --bucket=gs://java-spring-app --version=2']
+  args:
+    - '-c'
+    - |
+      if [ $? -eq 0 ]; then
+        gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --bucket=gs://java-spring-app --version=2
+      else
+        echo "Unit tests failed. Deployment aborted."
+      fi
 timeout: '1600s'
-# - name: 'gcr.io/cloud-builders/gcloud'
-#   entrypoint: 'gcloud'
-#   args: ['app', 'deploy', '--project=augmented-voice-396916', '--version=1', '/workspace/target/spring-boot-web-0.0.1-SNAPSHOT.jar']
